#!/bin/bash

Initialize() {
   los=-0.1
   gmtset HEADER_FONT_SIZE 14
   gmtset HEADER_OFFSET -0.2
   gmtset LABEL_FONT_SIZE 11
   gmtset LABEL_OFFSET $los
   gmtset ANNOT_FONT_SIZE 9
   gmtset ANNOT_OFFSET 0.05

	dirM=/home/tianye
	if [ ! -e ${dirM} ]; then
		dirM=/projects/yeti4009
	fi
   FTANexe=${dirM}/code/Programs/FTAN_amp_snr_predgrv/aftani_c_pgl_amp

	#Filter=${dirM}/code/Programs/Filter/Filter
	Filter=`which SAC_filter`
   Pssac=`which pssac`
   SAC=${SACHOME}'/bin/sac '${HOME}'/usr/macros/sacinit.m'
}

PlotSac() {
   sacf=$1
   Xoffset=$2
   Yoffset=$3
   pwd | psxy -R -J -O -K -X${Xoffset} -Y${Yoffset} >> $psout
   if [ ! -e $sacf ]; then echo $sacf" not found!" ; exit; fi
   #gmtset HEADER_OFFSET -1.2
   #gmtset LABEL_OFFSET -0.3
   xmrk=300
   xtic=50
   ymrk=10
   ytic=0.05
   tmax=800
   ### filter to 5 - 50 sec ###
   $Filter $sacf -1 0.02 0.3 6 5 $sacf'_ft'
   amax=`saclst depmin depmax f $sacf'_ft' | awk '{if(-$2>$3){print -$2*1.1}else{print $3*1.1}}'`
   REG=-R0/${tmax}/-${amax}/${amax}
   SCA=-JX4.0i/1.0i
   #gmtset LABEL_OFFSET -1.
   gmtset LABEL_OFFSET -0.5
   $Pssac $REG $SCA -Ba${xmrk}f${xtic}:"time (sec)":/:$label:wESn -O -K $sacf'_ft' >> $psout
   gmtset LABEL_OFFSET $los
   #gmtset LABEL_OFFSET $los
   ### label the sac info ###
   t_info=`saclst kevnm kstnm dist user0 f $sacf | awk '{printf "%s - %s:   Dist=%.0f km   TLen=%d days",$2, $3, $4, $5}'`
   echo 0.3 11.6 12 0 20 LT $t_info | pstext -R0/10/0/10 -Wwhite,O3/70/70/70 -J -O -K -N -P >> $psout
}

RunFTAN() {
   sacf=$1
   DispGrv=$2
   DispPhv=$3
   param=$4
   echo $param" "$sacf" 1" > param_R.dat
   $FTANexe param_R.dat $DispPhv $DispGrv 0.008
   rm -f param_R.dat
}

PlotFTAN() {
   ### plot FTAN diagram
   sacf=$1
   Xoffset=$2
   Yoffset=$3
   No=$4
   SCAx=4.0i
   SCAy=3.5i
	if [ $praw == 1 ]; then
	   ampf=${sacf}_1_AMP 
	   disf=${sacf}_1_DISP.0
	else
	   ampf=${sacf}_2_AMP 
	   disf=${sacf}_2_DISP.1
	fi
   dirpair=.
   REG=`echo $perl $perh | awk '{print "-R"log($1)"/"log($2)"/0.5/4.5"}'`
   REG_L=`echo $perl $perh | awk '{print "-R"log($1*0.8)"/"log($2*1.2)"/0.4/5.4"}'`
   rm -f ${dirpair}/${sacf}_amp_tmp ${dirpair}/${sacf}_amp.grd
   if [ ! -e ${dirpair}/${sacf}_amp_tmp ]; then
      #Npts=`more $ampf | wc -l` 
      #Nfre=`awk 'BEGIN{old=-1.; count=0}{if($1!=old){count++; old=$1}}END{print count}' $ampf`
      #Nvel=`echo $Npts $Nfre | awk '{print $1/$2}'`
      #step=`echo $Nfre $Nvel | awk '{step=int(0.04*$2/$1); if(step==0){step=1} print step}'`
      #awk -v step=$step 'BEGIN{old=-1.}{if(Npt%step==0){print log($1),$2,$3}; Npt++; if($1!=old){Npt=0; old=$1}}' $ampf > ${dirpair}/${sacf}_amp_tmp
      awk '{print log($1), $2, $3}' $ampf > ${dirpair}/${sacf}_amp_tmp
   fi
   if [ ! -e ${dirpair}/${sacf}_amp.grd ]; then
      #nearneighbor ${dirpair}/${sacf}_amp_tmp -G${dirpair}/amp.grd -I0.01 $REG -S0.2 -N6/2
      #surface ${dirpair}/${sacf}_amp_tmp -G${dirpair}/amp.grd -I0.01 $REG_L -T0.2
      xyz2grd ${dirpair}/${sacf}_amp_tmp -G${dirpair}/amp.grd -I0.01 $REG
      grdfilter ${dirpair}/amp.grd -D0 -Fg0.5 -G${dirpair}/${sacf}_amp.grd $REG
      #grdfft ${dirpair}/amp.grd -G${dirpair}/${sacf}_amp.grd -A0 -F-/-/0.05/0.01
      rm -f ${dirpair}/amp.grd
   fi
   #_fcpt=${dirpair}'/FTAN'${No}'.cpt'
   _fcpt=/projects/yeti4009/code/Script/FTAN/FTAN.cpt
	if [ ! -e ${_fcpt} ]; then
		_fcpt=~/code/Script/FTAN/FTAN.cpt
	fi
   grdimage $REG -JX${SCAx}/${SCAy} ${dirpair}/${sacf}_amp.grd -C$_fcpt -O -K -X${Xoffset} -Y${Yoffset} >> $psout
   #grdcontour -R -J ${dirpair}/${sacf}_amp.grd -C10 -W.5p,black -O -K >> $psout
   REG=-R${perl}/${perh}/0.5/4.5
   psbasemap $REG -JX${SCAx}l/${SCAy} -Ba3f3:"period (sec)":/a1.0f0.5:"group vel (km/s)"::."":WeSn -V -O -K >> $psout
   #awk '{print $3,$4}' $disf | psxy -R -J -Ba0.5f0.1:"group/phase vel (km/s)":/a3f3:."Dispersion":WSne -Sc.1 -Gred -A -O -K >> $psout
   #awk '{print $3,$5}' $disf | psxy -R -J -Sc.1 -Gblue -A -O -K >> $psout
   awk '{print $3,$4}' $disf | psxy -R -J -Sc.15 -W6 -Gwhite -A -O -K >> $psout
   awk '{print $3,$5}' $disf | psxy -R -J -Sc.15 -W6 -Gsteelblue -A -O -K >> $psout
	\rm -f ${sacf}_1_AMP ${sacf}_1_DISP.1 ${sacf}_2_AMP ${sacf}_2_amp_snr ${sacf}_2_DISP.0 ${sacf}_amp.grd ${sacf}_amp_snr ${sacf}_amp_tmp ${sacf}_ft #${sacf}_cld
}


### main ###

if [ $# != 6 ] && [ $# != 8 ]; then
	echo "Usage: "$0" [sacf] [vmin] [vmax] [permin] [permax] [plot raw FTAN? (0=no, 1=yes)] [disp_ref_grv] [disp_ref_phv]"
	exit
fi

Initialize

sacf=$1
vmin=$2
vmax=$3
perl=$4
perh=$5
praw=$6
if [ $# == 8 ]; then
	frefG=$7
	frefP=$8
else
   frefG="I_dont_believe_this_file_exists"
   frefP=${dirM}"/code/Programs/head/OBS_phvel.dat"
fi

psout=${sacf}_FTAN.ps
rm -f $psout
pwd | psxy -Rg -JX1 -K -P > $psout

#param='-1 0.15 4.5 0.8 35. 30. 2.0 3. 0.99 8. 15. 1.5 3.0 0.6 3.'
RunFTAN ${sacf} $frefG $frefP '-1 '$vmin' '$vmax' '$perl' '$perh' 30. 2.0 3. 0.99 8. 15. 1.5 3.0 0.6 3.'
PlotFTAN ${sacf} 3. 5. 1
PlotSac ${sacf} 0. 10.
echo "-0.5 14.4 15 0.0 4 LT (a)" | pstext -R0/10/0/10 $SCA -V -O -K -N >> $psout

pwd | psxy -R -J -O >> $psout
echo $psout


