#!/bin/csh
if ($#argv != 5) then
  echo "USAGE: C_plot_input_region [data infile] [region_infile] [resolution] [tension] [inter_sta_dis(km)]"
  exit 1
endif
set input_map = $argv[1]
set REG = `more $argv[2]`
set res = $argv[3]
set bdis = $argv[5]
set temp1=`echo $input_map | awk -F/ '{print $NF}'`
set temp2=`echo $argv[2] | awk -F/ '{print $NF}'`
set tomo = $temp1'.'$temp2'.grd'
gmtset BASEMAP_TYPE fancy
rm -f $tomo
blockmean $input_map $REG -I$bdis'km' > $temp1'.'$temp2'.txt1'
blockmean $temp1'.'$temp2'.txt1' $REG -F -I$bdis'km' > $temp1'.'$temp2'.txt'
surface $temp1'.'$temp2'.txt' -T$argv[4] -G$tomo -I$res $REG
#triangulate $input_map -G$tomo -I$res $REG
#nearneighbor $input_map -G$tomo -I$res $REG -S260k -N6/4
if (-e $tomo )then
grd2xyz $tomo $REG > $input_map".HD"
#grep -v 'NaN' $input_map".HD~" > $input_map".HD"
#rm $input_map".HD~"
endif
rm -f $tomo $temp1'.'$temp2'.txt' $temp1'.'$temp2'.txt1'
