#!/bin/csh
if ($#argv != 1) then
  echo "USAGE: C_plot_westUS_wk [data infile]"
  exit 1
endif
set input_map = $argv[1]
set out_name = `echo $input_map | cut -d. -f1`
set v1v2 = `echo $input_map | cut -d. -f3`
set output_am = $out_name"_am."$v1v2
awk '{print $1,$2,$5}' $input_map > $output_am
set REG = -R248/258/34/43

gmtset BASEMAP_TYPE fancy
surface $output_am -T0.0 -Gtomo.grd -I0.1 $REG
grd2xyz tomo.grd $REG > $output_am".HD"
