#!/bin/csh
if ($#argv != 1) then
echo "USAGE: TXT2CPT [input file]"
exit
endif

set in_map=$argv[1]
#set avg=`awk 'BEGIN{avg=0}{avg+=$3}END{print avg/NR}' $in_map`
#set avg_high_end=`awk -v avg=$avg 'BEGIN{avg_h=0;N=0}{if($3>avg){avg_h+=$3;N+=1}}END{print 3*avg_h/N-2*avg}' $in_map`
#set avg_low_end=`awk -v avg=$avg 'BEGIN{avg_l=0;N=0}{if($3<avg){avg_l+=$3;N+=1}}END{print 3*avg_l/N-2*avg}' $in_map`
set avg_high_end=`awk 'BEGIN{avg_h=0;N=0}{if($3>0){avg_h+=$3;N+=1}}END{if(N==0){print 0}else{print 3*avg_h/N}}' $in_map`
if( `echo $avg_high_end | awk '{if($1==0){print 1}else{print 0}}'` )then
echo "-1e-5 255 255 0 1e-5 255 255 0\
B 0 0 0\
F 100 0 170\
N 128 128 128\" > $in_map.cpt
#break
endif

set avg_low_end=`awk 'BEGIN{avg_h=0;N=0}{if($3<0){avg_h+=$3;N+=1}}END{if(N==0){print 0}else{print 3*avg_h/N}}' $in_map`
set high_end=`awk 'BEGIN{high=-99999}{if($3>high){high=$3}}END{print high}' $in_map`
set low_end=`awk 'BEGIN{low=99999}{if($3<low){low=$3}}END{print low}' $in_map`
#echo $avg,$avg_high_end,$high_end,$avg_low_end,$low_end
if ( `echo $high_end $avg_high_end | awk '{if($1>$2){print 1}else{print 0}}'` ) then
 set high_end=$avg_high_end
endif
if ( `echo $low_end $avg_low_end | awk '{if($1<$2){print 1}else{print 0}}'` ) then
 set low_end=$avg_low_end
endif

if( `echo $high_end | awk '{if($1<0){print 1}else{print 0}}'` ) then
  set high_end=`echo $high_end | awk '{print -$1}'`
endif
if( `echo $low_end | awk '{if($1<0){print 1}else{print 0}}'` ) then 
  set low_end=`echo $low_end | awk '{print -$1}'`
endif
#set avg=`echo "200*$avg/2*0.01" | bc`
#set inc_low=`echo "100*($avg-($low_end))/3*0.01" | bc`
#set inc_high=`echo "100*($high_end-($avg))/3*0.01" | bc`
if( `echo $high_end $low_end | awk '{if($1<$2){print 1}else{print 0}}'` )then
 set inc=`echo $low_end | awk '{printf "%.4g",$1/3}'`
else
 set inc=`echo $high_end | awk '{printf "%.4g",$1/3}'`
endif
set low3=`echo $inc | awk '{print -$1*3}'`
set low2=`echo $inc | awk '{print -$1*2}'`
set low1=`echo $inc | awk '{print -$1}'`
set high1=`echo $inc | awk '{print $1}'`
set high2=`echo $inc | awk '{print $1*2}'`
set high3=`echo $inc | awk '{print $1*3}'`
echo $low3" 0 0 0 "$low2" 255 0 0\
"$low2" 255 0 0 "$low1" 255 255 0\
"$low1" 255 255 0 0 255 255 255\
0 255 255 255 "$high1" 150 255 150\
"$high1" 150 255 150 "$high2" 100 185 255\
"$high2" 100 185 255 "$high3" 100 0 170\
B 0 0 0\
F 100 0 170\
N 128 128 128\" > $in_map.cpt
