#!/bin/csh
# Script for plotting the inversion results for the western US region from the weekly stacks.

# GET PLOTTING PARAMETERS
if ($#argv != 4) then
  echo "USAGE: C_plot [cpt file] [data infile] [region_infile] [resolution]"
  exit 1
endif

cp /home/tianye/code/Script/GMT/gmtdefaults4 ./.gmtdefaults4
#gmtset ANOT_FONT_SIZE 10
#gmtset BASEMAP_TYPE plain
#gmtset MEASURE_UNIT cm
set cptfile = $argv[1]
set input_map = $argv[2]
#set sta_list = $argv[3]

#set tomo_label=$input_map

foreach i (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20)
set event_label=`echo $input_map | sed s/'\.'/'_'/g | cut -d_ -f$i`
if( `echo $event_label | awk '{print length}'` == 14 )then
break
endif
end

set title=`echo $input_map | sed s/'\.'/'_'/g | cut -d_ --complement -f$i | sed s/'_txt.*HD'/''/g | sed s/'_'/' '/g`

set out_name = `echo $input_map `
#set event = `echo $out_name | cut -d/ -f8 | cut -d_ -f1`
set source = `echo $out_name | cut -d. --complement -f3`
set output_ps_file = ${out_name}.ps
echo "writing $output_ps_file file"
if (-f $output_ps_file) rm $output_ps_file

#set cptfile = /home/tianye/Script/GMT/cpt/$per

#cp /home/tianye/Script/GMT/head/topo_westUS2.xyz .
#set topofile = topo_westUS2.xyz
#set topogrd = topo.grd
#set topoint = topoint.grd
#set SCA = -Jm.87
set REG = `more $argv[3]`
set long1=`echo $REG | cut -d/ -f1 | sed s/'\-R'/''/` 
set long2=`echo $REG | cut -d/ -f2`
set long=`echo $long1 $long2 | awk '{print ($1+$2)/2}'`
#set REG = '-Rg'

set latimin=`echo $REG | cut -d/ -f3`
set latimax=`echo $REG | cut -d/ -f4`
set SCA = -JN$long/6i
#set SCA = '-Jm'`echo $latimax $latimin | awk '{printf "%.3f",12.7/($1-$2)}'`

#gmtset BASEMAP_TYPE fancy


# sample topography and tomography
#pwd | psxy -H $REG $SCA -Ba2f1g1/a2f1g1WeSn:."": -X1 -Y1.8 -P  -V -K  >! $output_ps_file
pwd | psxy -H $REG $SCA -X2.2 -Y8.0 -P  -V -K  >! $output_ps_file

#xyz2grd $topofile -G$topogrd -I4m -N-999 $REG -V
#grdgradient $topogrd -A90 -G$topoint -Nt -V

#psclip $REG $SCA -O -P -K -V << EOF >> $output_ps_file
#235 30
#235 50
#250 50
#250 30
#235 30
#EOF

set sms=`echo $argv[4] | awk '{print $1/10.0}'`
xyz2grd $input_map -Gtomo.grd -I$argv[4] -V $REG
grdsample tomo.grd -Q -Gtomo2.grd $REG -I$sms
grdimage $SCA $REG tomo2.grd -C$cptfile -Ba3f2/a3f2WESN:."$title": -X3 -O -P -K >> $output_ps_file
#psclip -C -O -K >> $output_ps_file
#grdcontour $SCA $REG tomo.grd -C$cont_dis -W.5p,black -O -K >> $output_ps_file

pscoast $SCA $REG -A100 -N1/3/0/0/0 -N2/3/0/0/0 -O -K -W3 -S135/206/235 >> $output_ps_file
# removed gridlines (uncomment to replace)
#pscoast $SCA $REG -Ba5f5g2.5/a5f5g2.5WeSn:."": -W3/0/0/0 -S135/206/235  -O -K >> $output_ps_file
#pscoast $SCA $REG -Ba60f10/a30f5WESN:."": -W3/0/0/0 -S135/206/235 -O -K >> $output_ps_file



#psxy $temp_name".good5.ph.txt" $SCA $REG -St.25 -W3 -G255/255/255 -O -K >> $output_ps_file
#psxy source.txt $SCA $REG -Sa.8 -W3 -G255/255/255 -O -K >>$output_ps_file
#psxy target.txt $SCA $REG -Sa.8 -W3 -G255/255/255 -O -K >>$output_ps_file

#psxy $temp_name".good5.ph.txt" $SCA $REG -St.25 -W3  -O -K >> $output_ps_file
#psxy $source $SCA $REG -St.2 -W3  -O -K >>$output_ps_file
#psxy target.txt $SCA $REG -Sa.8 -W3  -O -K >>$output_ps_file

psxy /home/tianye/code/Programs/head/wus_province_II.dat $SCA $REG -W5/255/0/0 -M"99999 99999"  -O -K >> $output_ps_file
#psxy /home/tianye/Script/GMT/head/wus_province_II.dat $SCA $REG -W5/255/0/0 -m"99999 99999"  -O -K >> $output_ps_file
psscale  -C$cptfile -P -D-3.5/7.5/15/1 -O -K -L  >> $output_ps_file

while(1)
echo "Enter (lon_lat) or (#) to stop"
set loc=$<
if ( $loc == '#' ) break
echo $loc | awk -F_ '{print $1,$2}' | psxy $REG $SCA -Sa.3 -W3 -G255/0/0 -O -K >> $output_ps_file
end
#echo 236 40 | psxy $REG $SCA -Sa.3 -W3 -G255/0/0 -O -K >> $output_ps_file
#echo 239 45 | psxy $REG $SCA -Sa.3 -W3 -G255/0/0 -O -K >> $output_ps_file
#echo 290 55 | psxy $REG $SCA -Sa.3 -W3 -G255/0/0 -O -K >> $output_ps_file
#echo $clong $clati | psxy $SCA $REG -Sc.5 -W4/128/128/128 -Gred -O -K >> $output_ps_file

#foreach src ( 183@53.5 356@49 359@67 154.5@-17 )
#set slong=`echo $src | cut -d@ -f1`
#set slati=`echo $src | cut -d@ -f2`
#set loc=`project -C$slong'/'$slati -E$clong'/'$clati -G20000 -Q -L0/20000 | awk 'NR==2{print $1,$2}'`
#echo $clong" "$clati"\n"$loc | psxy $REG $SCA -W10,red -O -K >> $output_ps_file
#end

#awk '{print $2,$3" 10 0 1 1 "$1}' $argv[5] | pstext $SCA $REG -Gblack -O -K >> $output_ps_file

# LABELS
pstext -R0/10/0/10 -JX10c  -V -O -N -G0 -Y3c -X0.5c << END >>  $output_ps_file

3 -4.5 16 0.0 7 CB  event: $event_label
#5.50 -6.75 16 0.0 7 CB  phase velocity (km/s)
END

\rm tomo.grd tomo2.grd topo_westUS2.xyz
#xv $output_ps_file &

