#!/usr/bin/ksh
#
# Note, if ksh is not available, you can use
# another shell like zsh
#
##################################################
##################################################
# This script will compile all executable programs
# that are required by the FMM based tomographic
# inversion routine FMST. Additional programs for
# plotting, computing model roughness etc. are
# also compiled. See accompanying documentation
# for further details
##################################################
##################################################
#
# YOU MUST SPECIFY A FORTRAN 90 COMPILER!!!!
# Compiler options can be included at this stage
# if deemed necessary by the user.
#
##################################################
F90=ifort
##################################################
#
# Enter the directory called "source" and compile
# all programs
#
##################################################
cd source
$F90 -o fm2dss fm2dss.f90
echo " "
echo "Compilation of fm2dss complete"
$F90 -o grid2dss grid2dss.f90
echo " "
echo "Compilation of grid2dss complete"
$F90 -o misfitss misfitss.f90
echo " "
echo "Compilation of misfitss complete"
$F90 -o residualss residualss.f90
echo " "
echo "Compilation of residualss complete"
$F90 -o resplotss resplotss.f90
echo " "
echo "Compilation of resplotss complete"
$F90 -o subinvss subinvss.f90
echo " "
echo "Compilation of subinvss complete"
$F90 -o synthtss synthtss.f90
echo " "
echo "Compilation of synthtss complete"
$F90 -o tslicess tslicess.f90
echo " "
echo "Compilation of tslicess complete"
##################################################
#
# Move all executables to directory ../bin
#
##################################################
mv fm2dss grid2dss misfitss residualss ../bin
mv resplotss subinvss synthtss tslicess ../bin
##################################################
##################################################
#Compilation is now complete
##################################################
##################################################
cd ../
echo " "
echo "Compilation complete"
