#!/bin/csh
#echo on
if ($#argv != 2) then
  echo "USAGE: correct_2pi_curvature [rname] [per]"
  exit 1
endif

#cd $argv[2]

#set REG = `more $argv[1]`
set per=$argv[2]
#foreach sta (`ls *_center_ph_amp_map | cut -d_ -f1`)
#foreach sta (M12A)
/home/tianye/code/Programs/ASN/correct_2pi_v1 $argv[1]"_ph_amp_map" $per 5
/home/tianye/code/Script/GMT/C_plot_travel_positive $argv[1]"_ph_amp_map_v1" region_$argv[1] 0.1
mv $argv[1]"_ph_amp_map_v1.HD" $argv[1]"_ph_map_v1.HD"
/home/tianye/code/Script/GMT/C_plot_ASN_am  $argv[1]"_ph_amp_map_v1" region_$argv[1]
/home/tianye/code/Programs/ASN/correct_curvature $argv[1] $per 5 0.05 0.05
#end

rm -f `wc $argv[1]"_ph_amp_map_v2" | grep "0       0       0" | awk '{print $4}'`
if( ! -e $argv[1]"_ph_amp_map_v2" ) exit 0
#/home/tianye/code/Script/GMT/C_plot_travel_positive $argv[1]"_ph_amp_map_v2" region_$argv[1] 0.1
#mv $argv[1]"_ph_amp_map_v2.HD" $argv[1]"_ph_map_v2.HD"
#/home/tianye/code/Script/GMT/C_plot_travel_T0.2 $sta"_center_ph_amp_map_v2" $argv[1]
/home/tianye/code/Script/GMT/C_plot_ASN_am $argv[1]"_ph_amp_map_v2" region_$argv[1]

#end
#cd ..
#end
